### ISSUE TITLE
Rename bamToCountMuts.py

### ISSUE THREAD

**Issue by scottrk** [Kennedy-Lab-UW/Duplex-Seq-Pipeline#11]
Script name is not very descriptive or accurate given how it works. MutationFreqFromVCF.py or similar is more correct given the changes that have been made.

**Comment by bkohrn** [comment]
Resolved by 9e95cfa46aff36d4713ead94c11ab7d46e855ff1 in the add_vcf_filters branch.  I did it there since the name change was such a minor thing that I didn't feel it was worthy of it's own branch.
