### ISSUE TITLE
dcs.countmuts to include depth

### ISSUE THREAD

**Issue by rrisques** [Kennedy-Lab-UW/Duplex-Seq-Pipeline#15]
Currently the dcs.countmuts file in the column called 'denominator' includes total number of nucleotides sequenced for a given gene or gene block (which typically correspond to exons). It would be ideal if there was another column for average depth. It could be simply calculated as the number of nucleotides sequenced divided by the length (number of nucleotides) of each block or gene.

**Comment by KennedyLabUW** [comment]
I hesitate to put that information in the mutation count file as it would mess up the formatting which is currently fairly easy to parse in excel. @bkohrn and I have discussed putting median and max depth information in the report and we could extend that to the gene and/or block level. Alternatively, we could just output that information as its own file.

**Comment by rrisques** [comment]
At the end of the report would be ideal, although it might get really long for large libraries. Otherwise in a separate output file would be fine too.

**Comment by bkohrn** [comment]
Just to be clear, you want a per-region average depth?  Or would you prefer if I added a column of the number of bases on the reference genome covered by that row?  Or both?

**Comment by bkohrn** [comment]
Actually, now that I think about it, there may already be a program that can handle this.  See bedtools coverage (https://bedtools.readthedocs.io/en/latest/content/tools/coverage.html)

**Comment by rrisques** [comment]
I'm out of town but càn check when back.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bkohrn** [comment]
Command for bedtools (to implement as separate step):
`bed12ToBed6 -i bedFile.bed | bedtools coverage -a stdin -b mySamp.dcs.final.bam -mean`

**Comment by bkohrn** [comment]
I just realized that I already implemented my own program for this; it seems to give the same mean depth as the bedtools program without requiring adding another program to the environment.
